### ISSUE TITLE
Blank plots

### ISSUE THREAD

**Issue by lkapelevich** [sglyon/PlotlyJS.jl#254] opened 2018-11-17 19:59 UTC
When I try to create a plot from my REPL I get a blank window with no content. Saving the plots with `savefig` does generate files correctly.

```
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

(v1.0) pkg> status
    Status `C:\Users\<...>\.julia\environments\v1.0\Project.toml`
  [7073ff75] IJulia v1.14.1
  [f0f68f2c] PlotlyJS v0.12.0+ #master (https://github.com/sglyon/PlotlyJS.jl.git)
```

**Comment by sglyon** [comment] 2018-11-19 13:08
Thank you for reporting. What version of Blink and WebIO do you have right now?

**Comment by lkapelevich** [comment] 2018-11-19 13:33
Blink v0.8.1 and WebIO v0.6.0

**Comment by JobJob** [comment] 2018-11-20 11:30
Does this fix it for you: `using Pkg; Pkg.add(PackageSpec(name="WebIO", version="v4.4.2"))`

**Comment by lkapelevich** [comment] 2018-11-20 14:07
Yes!

**Comment by versipellis** [comment] 2018-11-20 21:48
Running into this same issue with Blink v0.8.1 and WebIO v0.6.0, as well as WebIO v0.4.2.

**Comment by jonas-kr** [comment] 2018-11-21 11:55
Addition: The issue is not fixed by updating to WebIO v0.6.1. (Blink v.0.8.1 as well).

**Comment by amellnik** [comment] 2018-11-29 17:24
We tested this on two systems running MacOS and Ubuntu, and both times it was fixed by downgrading to WebIO v0.4.2.  Would it make sense to cut a new release with this requirement change until it can be resolved?

**Comment by azurefx** [comment] 2018-12-03 10:53
The same issue.
WebIO 0.6.1
Blink 0.9.0
PlotlyJS 0.12.0
Julia 1.0.0
Windows 10 1803 x64

**Comment by sglyon** [comment] 2018-12-03 18:36
I believe this has been fixed on the master branch.

Would someone here please:

- free WebIO (let it go back to >= 0.6): `(v1.0) pkg> free WebIO`
- checkout PlotlyJS `(v1.0) pkg> dev PlotlyJS`
- try to plot something

Thanks!

**Comment by amellnik** [comment] 2018-12-03 18:53
Using PlotlyJS master, this works with either WebIO 4.2 or 6.1 on MacOS.  I needed to build WebIO before it worked on 6.1.  Thanks!

**Comment by sglyon** [comment] 2018-12-03 18:55
Ok excellent. I'll publish a release

**Comment by versipellis** [comment] 2018-12-04 20:53
Works on Ubuntu 18.10 on the REPL.

**Closed** 2018-12-05 03:32 UTC
