### ISSUE TITLE
Require DataFrames failed

### ISSUE THREAD

**Issue by zhouyan** [sglyon/PlotlyJS.jl#169] opened 2018-01-29 07:06 UTC
I am getting the following warning when loading PlotlyJS after recent update. I do have DataFrames installed and it works fine. I can't make sense of the error message though. All appearance of `df` in `dataframe_api.jl` looks fine to me and the line in question according to the error message `522` does not exists

```
WARNING: Error requiring DataFrames from PlotlyJS:
LoadError: UndefVarError: df not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] err(::PlotlyJS.##264#271, ::Module, ::String) at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/require.jl:42
 [4] withpath(::PlotlyJS.##263#270, ::String) at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/require.jl:32
 [5] listenmod(::PlotlyJS.##262#269, ::Symbol) at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/require.jl:13
 [6] macro expansion at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/require.jl:52 [inlined]
 [7] (::PlotlyJS.##261#268)() at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/init.jl:17
 [8] __init__() at /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/Requires/src/init.jl:24
 [9] _include_from_serialized(::String) at ./loading.jl:157
 [10] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [11] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [12] _require(::Symbol) at ./loading.jl:441
 [13] require(::Symbol) at ./loading.jl:405
 [14] include_from_node1(::String) at ./loading.jl:576
 [15] include(::String) at ./sysimg.jl:14
 [16] eval(::Module, ::Any) at ./boot.jl:235
 [17] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [18] macro expansion at ./REPL.jl:97 [inlined]
 [19] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading /opt/fairtide/tools/pkgs/julia/0.6.2/share/julia/site/v0.6/PlotlyJS/src/dataframes_api.jl, in expression starting on line 522
```

**Comment by sglyon** [comment] 2018-01-29 13:56
Hmm, that is very strange.

Can you please post the code that you used when this error message comes about? I haven't seen it before, but perhaps with the exact sequence of commands I will be able to trigger the error also.

It would also be helpful to see the output of `Pkg.status()` so I know exactly what versions of PlotlyJS.jl and DataFrames.jl you are working with

**Comment by zhouyan** [comment] 2018-01-29 13:58
I am still trying to produce a MWE. Will update once I get it.

**Comment by sglyon** [comment] 2018-01-29 14:00
Ahh shoot, I actually see what the issue is... 

The docstring [here](https://github.com/sglyon/PlotlyJS.jl/blob/v0.9.0/src/dataframes_api.jl#L36) has a `$(mean(df[:X1])`, where the `$` actually makes Julia try to run that code.

I've fixed this on master. I will do a quick release so that issue goes away on the official released version of the package

**Comment by sglyon** [comment] 2018-01-29 15:47
I'm actually working on a larger set of updates right now that I won't be able to finish really quickly.

For now, will you please try `Pkg.checkout("PlotlyJS")` and try again?

**Comment by sglyon** [comment] 2018-02-02 16:34
This is now fixed in a released version of PlotlyJS.jl

a `Pkg.checkout("PlotlyJS")` and `Pkg.update()` should get you back on that version

**Closed by sglyon** 2018-02-02 16:34 UTC
